let $=nobyda(),run=EnvInfo();async function SwitchRegion(i){var e=$.read("BiliArea_Policy")||"📺 DomesticMedia";const n=$.read("BiliArea_CN")||"DIRECT",a=$.read("BiliArea_TW")||"🇹🇼 sub-policy",o=$.read("BiliArea_HK")||"🇭🇰 sub-policy",r=$.read("BiliArea_DF")||"🏁 sub-policy";var t=$.read("BiliArea_disabled")||"";const s=await $.getPolicy(e);var c=(()=>{let e;var t;return/\u50c5[\u4e00-\u9fa5]+\u6e2f|%20%E6%B8%AF&/.test(i)?(t=/\u50c5[\u4e00-\u9fa5]+\u53f0/.test(i),s==o||s==a&&t||(e=o)):/\u50c5[\u4e00-\u9fa5]+\u53f0|%20%E5%8F%B0&/.test(i)?s!=a&&(e=a):-404===i?s!=r&&(e=r):(-1!=i.indexOf("live_app")&&console.log("2222222"),s!=n&&(e=n)),e=$.isQuanX&&"direct"===s&&"DIRECT"===e?null:e})();if(c&&!t.includes($.ssid||void 0)){t=await $.setPolicy(e,c),e="true"===$.read("BiliAreaNotify"),c=SwitchStatus(t,s,c);if(e?console.log(`${/^(http|-404)/.test(i)||!i?"":i}
`+c):$.notify(/^(http|-404)/.test(i)||!i?"":i,"",c),t)return!0}return!1}function SwitchStatus(e,t,i){return e&&"number"!=typeof t?t+`  =>  ${i}  =>  🟢`:2===t?"切换失败, 策略组名未填写或填写有误 ⚠️":3===t?"切换失败, 不支持您的VPN应用版本 ⚠️":0===e?"切换失败, 子策略名未填写或填写有误 ⚠️":"策略切换失败, 未知错误 ⚠️"}function EnvInfo(){if("undefined"!=typeof $response){const t=JSON.parse($response.body),i=t.data||t.result||{};SwitchRegion(i.title||i.packages||(-404===t.code?-404:null)).then(e=>e?$done({status:$.isQuanX?"HTTP/1.1 408 Request Timeout":408,headers:{Connection:"close"},body:"{}"}):QueryRating(t,i))}else{var e=$request.url;const n={url:e.replace(/%20(%E6%B8%AF|%E5%8F%B0|%E4%B8%AD)&/g,"&")};SwitchRegion(e).then(()=>$done(n))}}async function QueryRating(e,t){try{var i,n,a,o,r,s,c,u,l,d,f,p,g;!("false"===$.read("BiliDoubanRating"))&&t.title&&e.data&&e.data.badge_info&&([i,n]=await Promise.all([GetRawInfo(t.title),GetRawInfo(t.origin_name)]),a=e.data.publish.release_date_show.split(/^(\d{4})/)[1],o=t.staff&&t.staff.info||"",r=t.actor&&t.actor.info||"",s=t.celebrity&&t.celebrity.map(e=>e.name).join("/")||"",c=[t.title,t.origin_name,o+r+s,a],[u,l,d,f,p]=ExtractMovieInfo([...i,...n],c),g=JSON.stringify(e.data.modules).replace(/"\u53d7\u9650"/g,'""').replace(/("area_limit":)1/g,"$10"),e.data.modules=JSON.parse(g),e.data.detail=e.data.new_ep.desc.replace(/连载中,/,""),e.data.badge_info.text="⭐️ 豆瓣："+($.is403?"查询频繁！":`${u||"无评"}分 (${l||"无评价"})`),e.data.evaluate=`${e.data.evaluate||""}

豆瓣评分搜索结果: `+JSON.stringify(p,0,1),e.data.new_ep.desc=d,e.data.styles.unshift({name:"⭐️ 点击此处打开豆瓣剧集详情页",url:"https://m.douban.com/"+(f?`movie/subject/${f}/`:"search/?query="+encodeURI(t.title))}))}catch(e){console.log(`Douban rating: 
${e}
`)}finally{$done({body:JSON.stringify(e)})}}function ExtractMovieInfo(e,i){e=[...new Set(e.map(e=>JSON.stringify(e)))].map(e=>JSON.parse(e)).filter(e=>{var t;return e.accuracy=0,e.name&&i[0]&&(e.name.includes(i[0].slice(0,4))&&e.accuracy++,e.name.includes(i[0].slice(-3)))&&e.accuracy++,e.origin&&i[1]&&(e.origin.includes(i[1].slice(0,4))&&e.accuracy++,e.origin.includes(i[1].slice(-3)))&&e.accuracy++,e.pd&&i[2]&&(t=e.pd.split("/").filter(e=>i[2].includes(e)),e.accuracy+=t.length),e.year&&i[3]&&e.year==i[3]&&e.accuracy++,Boolean(e.accuracy)});let n={};e.reduce((e,t)=>t.accuracy>e?(n=t).accuracy:e,0);return[n.rating,n.folk,n.name,n.id,e]}function GetRawInfo(o){let r=[],s=Date.now();return new Promise(a=>{if(!o)return a(r);$.get({url:"https://www.douban.com/search?cat=1002&q="+encodeURIComponent(o),headers:{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15",Cookie:JSON.stringify(s)}},(e,t,i)=>{if(e)console.log(`Douban rating: 
${o}
Request error: ${e}
`);else{/\u767b\u5f55<\/a>\u540e\u91cd\u8bd5\u3002/.test(i)&&($.is403=!0);var n=i.replace(/\n| |&#\d{2}/g,"").match(/\[(\u7535\u5f71|\u7535\u89c6\u5267)\].+?subject-cast\">.+?<\/span>/g)||[];for(let e=0;e<n.length;e++)r.push({name:n[e].split(/\}\)">(.+?)<\/a>/)[1],origin:n[e].split(/\u540d:(.+?)(\/|<)/)[1],pd:n[e].split(/\u539f\u540d.+?\/(.+?)\/\d+<\/span>$/)[1],rating:n[e].split(/">(\d\.\d)</)[1],folk:n[e].split(/(\d+\u4eba\u8bc4\u4ef7)/)[1],id:n[e].split(/sid:(\d+)/)[1],year:n[e].split(/(\d+)<\/span>$/)[1]});e=((Date.now()-s)/1e3).toFixed(2);console.log(`Douban rating: 
${o}
${r.length} movie info searched. (${e} s)
`)}a(r)})})}function nobyda(){const a="undefined"!=typeof $httpClient,t="undefined"!=typeof $loon,o="undefined"!=typeof $task,r="undefined"!=typeof $network&&"undefined"!=typeof $script;var e=o&&"undefined"!=typeof $environment?$environment.ssid:r&&$network.wifi?$network.wifi.ssid:t?JSON.parse($config.getConfig()).ssid:void 0;const s=e=>e?(e.status?e.statusCode=e.status:e.statusCode&&(e.status=e.statusCode),e):null;return{getPolicy:i=>{return r?"undefined"==typeof $httpAPI?3:new Promise(t=>{$httpAPI("GET","v1/policy_groups/select",{group_name:encodeURIComponent(i)},e=>t(e.policy||2))}):t?void 0===$config.getPolicy?3:$config.getPolicy(i)||2:o?"undefined"==typeof $configuration?3:new Promise(t=>{$configuration.sendMessage({action:"get_policy_state"}).then(e=>{e.ret&&e.ret[i]?t(e.ret[i][1]):t(2)},()=>t())}):void 0},setPolicy:(e,i)=>{return r&&"undefined"!=typeof $httpAPI?new Promise(t=>{$httpAPI("POST","v1/policy_groups/select",{group_name:e,policy:i},e=>t(!e.error||0))}):t&&void 0!==$config.getPolicy?$config.setSelectPolicy(e,i)||0:o&&"undefined"!=typeof $configuration?new Promise(t=>{$configuration.sendMessage({action:"set_policy_state",content:{[e]:i}}).then(e=>t(!e.error||0),()=>t())}):void 0},isSurge:r,isQuanX:o,isLoon:t,notify:(e,t,i)=>{console.log(e+`
${t}
`+i),o&&$notify(e,t,i),a&&$notification.post(e,t,i)},read:e=>o?$prefs.valueForKey(e):a?$persistentStore.read(e):void 0,ssid:e,get:(e,n)=>{o&&(e.method="GET",$task.fetch(e).then(e=>{n(null,s(e),e.body)},e=>n(e.error,null,null))),a&&(r&&(e.headers["X-Surge-Skip-Scripting"]=!1),$httpClient.get(e,(e,t,i)=>{n(e,s(t),i)}))}}}